apiVersion: apps/v1
kind: Deployment
metadata:
  name: creds-frontend
spec:
  selector:
    matchLabels:
      app: creds-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: creds-frontend
    spec:
      containers:
      - name: creds-frontend
        image: rahulvivaops/vivaopsprojects-creds-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://localhost:60652/api/data
---
apiVersion: v1
kind: Service
metadata:
  name: creds-frontend
spec:
  type: NodePort
  selector:
    app: creds-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
