apiVersion: apps/v1
kind: Deployment
metadata:
  name: creds-backend
spec:
  selector:
    matchLabels:
      app: creds-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: creds-backend
    spec:
      containers:
      - name: creds-backend
        image: rahulvivaops/vivaopsprojects-creds-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_CREDS_URL
          value: mongodb://mongo-creds:27017/creds
---
apiVersion: v1
kind: Service
metadata:
  name: creds-backend
spec:
  type: NodePort
  selector:
    app: creds-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002